import logging
import logging.config

"""
Class that allows managing the logs generated by api alerting tool
"""


class Logger:
    """
    Method that writes the logs generated by the application.
    Parameters:
    self -- An instantiated object of the Logger class.
    message -- Message to be shown in the log.
    type_log -- Type of log to write.
    """
    def createLogAlert(self, message, type_log):
        logging.config.fileConfig(fname='config/logger.conf', disable_existing_loggers=False)
        logger = logging.getLogger('AlertingTool')
        if type_log == 1:
            logger.debug(message)
        if type_log == 2:
            logger.info(message)
        if type_log == 3:
            logger.warning(message)
        if type_log == 4:
            logger.error(message)
        if type_log == 5:
            logger.critical(message)